[language-server.harper]
command = "harper-ls"
args = ["--stdio"]

[language-server.neocmake]
command = "neocmakelsp"
args = ["--stdio"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "cmake"
language-servers = ["neocmake", "cmake-language-server"]

[[language]]
name = "ebuild"
scope = "source.ebuild"
injection-regex = "ebuild"
file-types = ["ebuild", "eclass"]
indent = { tab-width = 4, unit = "    " }
language-servers = ["ebuild"]
grammar = "bash"

[[language]]
name = "fortran"
indent = { tab-width = 3, unit = "   " }
formatter = { command = "fprettify", args = ["--stdout"] }

[[language]]
name = "python"
language-servers = ["pyright", "pylsp", "ruff", "harper"]
formatter = { command = "ruff", args = ["format", "-"] }

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
